<?php
/**
 * Those events are required.
 * Do not edit this file.
 */
return array(

	'agl_set_request_before' => array(
		'more/locale/observer' => array(
			'translateRequest'
		)
	),

	'agl_set_request_after' => array(
		'more/locale/observer' => array(
			'redirectOrig'
		)
	)

);
